### PR TITLE
Add compatibility with OpenSearch 2.11.0

### PR DESCRIPTION
**Pull request by AlexRuiz7**
### Description

This PR bases the Wazuh dashboard security plugin fork on OpenSearch 2.11.0, migrating all the changes from previous versions of the fork.

### Issues Resolved

- #30 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AlexRuiz7** [comment]
## Integration tests failure

```
FAIL test/jest_integration/saml_multiauth.test.ts (19.831 s)
  start OpenSearch Dashboards server
    ✕ Login to Dashboards and resume from nextUrl (5955 ms)
    ✕ Login to Dashboards without nextUrl (5984 ms)
```

**Comment by yenienserrano** [comment]
In opensearch they solved the integration test problem in this [issue](https://github.com/opensearch-project/security-dashboards-plugin/pull/1641).

**Review by yenienserrano — APPROVED** [review]
LGTM

**Review by AlexRuiz7 — COMMENTED** [review]
LGTM

**Pull request merged**
